; HEADER_BLOCK_START
; generated by Flash Studio 1.7.15 on 2026-08-30 at 13:53:39
; total layer number: 100
; filament_density: 0
; filament_diameter: 1.75
; max_z_height: 20.00
; filament: 1
; HEADER_BLOCK_END

; filament used [mm] = 1336.29
; filament used [cm3] = 3.21
; <filament id="1" tray_info_idx="GFL99" type="PLA" color="#F2754E" used_m="1.31" used_g="0.00" />
; total filament used [g] = 0.00
; total filament cost = 0.00
; total layers count = 100
; estimated printing time (normal mode) = 19m 18s
; estimated first layer printing time (normal mode) = 15s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
