; HEADER_BLOCK_START
; generated by Flash Studio 1.7.15 on 2026-08-30 at 13:54:07
; total layer number: 100
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 20.00
; filament: 1
; HEADER_BLOCK_END

; filament used [mm] = 1838.71
; filament used [cm3] = 4.42
; filament used [g] = 5.48
; <filament id="1" tray_info_idx="GFL99" type="PLA" color="#F2754E" used_m="1.81" used_g="5.41" />
; total filament used [g] = 5.48
; total filament cost = 0.00
; total layers count = 100
; estimated printing time (normal mode) = 29m 19s
; estimated first layer printing time (normal mode) = 15s

; CONFIG_BLOCK_START
